# Generated by Django 4.2 on 2023-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(null=True, verbose_name='Date of the beginning of the tournament')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Date of the end of the tournament')),
                ('nb_pools', models.IntegerField(verbose_name='Number of pools')),
                ('nb_teams_in_pool', models.IntegerField(verbose_name='Number of teams per pool')),
            ],
        ),
    ]
