# Generated by Django 4.2 on 2023-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournoi',
            old_name='place',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
    ]
