# Generated by Django 4.2 on 2023-04-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_team_poule_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the match')),
                ('time', models.TimeField(verbose_name='Time of the match')),
                ('location', models.CharField(max_length=200)),
                ('score_1', models.IntegerField(verbose_name='Score of team 1')),
                ('score_2', models.IntegerField(verbose_name='Score of team 2')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.poule', verbose_name='Pool')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='tournaments.team', verbose_name='Team 1')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='tournaments.team', verbose_name='Team 2')),
            ],
        ),
    ]
