# Generated by Django 4.2 on 2023-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score of team 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score of team 2'),
        ),
    ]
